services:
  - type: web
    name: mindjournal
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && cd ../frontend && npm install && npm run build
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
